### PR TITLE
Adding .DS_Store to .gitignore & Core Install on AKS with Helm

### PR DESCRIPTION
**Pull request by ZachDZimmerman**
@cloudbees/team-professional-services 

Any and all feedback is welcomed. Please tear this doc apart 😄 
Will iterate on the document as needed.

SIG work for modern cloud & K8s

### CODE REVIEW

**Comment by ZachDZimmerman** [comment]
https://cloudbees.atlassian.net/browse/PSSIG-43

**Comment by lcorbo-cb** [comment]
Would you be alright with naming your project folder something more descriptive than "AKS"?  Maybe "core-v2-mod-manage-cli-aks-workstation-config" or something similar? 

Also there is no code in this PR, only a MD file.  Would it be possible to include a script automating the steps discussed?

**Comment by mhicks-cloudbees** [comment]
> Would you be alright with naming your project folder something more descriptive than "AKS"? Maybe "core-v2-mod-manage-cli-aks-workstation-config" or something similar?

It's ok for us to use "core-v2" terminology internally, but not externally and I'd still advise against it internally.  Please at least use "Core Modern" (versus "Core Traditional").

**Comment by ZachDZimmerman** [comment]
Sorry, @lcorbo-cb and @mhicks-cloudbees I never received notifications on your comments. Thanks for the feedback. @lcorbo-cb this is definitely something that can be scripted out, however, this is explicitly for using Azure Cloud Shell. Next steps for sprint work was to make a terraform project

**Comment by ZachDZimmerman** [comment]
https://cloudbees.atlassian.net/browse/PSSIG-65

**Pull request merged**
